chore: set zinnia_runtime version in Cargo.toml
Before this change, we were not able to publish zinnia CLI crate.

```
❯ cargo publish -p zinnia
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `zinnia_runtime` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

Signed-off-by: Miroslav Bajtoš <oss@bajtos.net>